language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: BOQhGWCQUFZaoBA2GI53xJEz+m7G0T8WCYb2CSAiTgU1Y0F5W8pEwk5ZfnxssGW+cbXRfltiXAiGnxQyALbB96Hpms6iaW1mbIRyLzwiShke6nca+NaWbIwr3xTo3Yhph6ZH+MIavoX+2JkGF6XKaGpbwGjEgFYQGU57wTTwHhy9R+6swUpAHvAetD2roY1DMI6bsum9YA48AKK0Cmble6lcsU3JmYEZFrNm3FWDLmOMXEHCyuMRa+QoG5tLU+/+IK1zlSCsCWlCxnLND1vF4Tn4DRMs//L+e9bHv8WWJRF5WAgOqvTgWt0/m3jl5mAsQRni8cI41cXpPrqzS8N058GteiBQEfCjIP9QcBpE1HiwUulYfyVcwxpOamdqaEYmfSCjQ+vQ20wBo3+RAzzO6aVImbv2QNCrf1wrmReCDSrJM0DXFQClwOpxxmVoy6ULvaa/cPV8keLiLBNKnrlomBHhbMMyPZ5GKFWsT+xHZntn+PAudyxje0kwn2+A/QblpnyHbHHcLnXztGi/hc7PqAFlcfoHQdZ2O8RvUkyITPWofEPsyjRwLAiZp8o4bZgLOLg/6Fro5+Njoz+cKjllu85I5ICdLVz1sEmjickqoKJ7sdFzLCYks5UWcjz+ag/Q9swosziPRRyWQgqIBLb2bsA4Ni51/iWN9Czjzk9Gl6E=
    app: api-upload-khan-squash
